BOFNAME := dcom
CC_x64 := x86_64-w64-mingw32-gcc
CC_x86 := i686-w64-mingw32-gcc

all:
	$(CC_x64) -o $(BOFNAME).x64.o -c BOF-IShellWindows-DCOM.c
	$(CC_x86) -o $(BOFNAME).x86.o -c BOF-IShellWindows-DCOM.c
